name: Update Weather Data

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: {}

jobs:
  update-weather:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Run weather data script
        run: python klga_request.py

      - name: Commit updated CSV if changes exist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "coopfos"
          git config --global user.email "cooperbfoster@gmail.com"
          git add weather_data.csv
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update weather data"
            git push "https://x-access-token:${GITHUB_TOKEN}@github.com/coopfos/KLGA.git" HEAD:main
          fi