name: Update Weather Data

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: {}

jobs:
  update-weather:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Run weather data script
        run: python klga_request.py

      - name: Commit updated CSV if changes exist
        run: |
          git config --global user.name "coopfos"
          git config --global user.email "cooperbfoster@gmail.com"
          git add weather_data.csv
          git diff-index --quiet HEAD || (git commit -m "Update weather data" && git push)